// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgOO7dqA37r61O3hAm2CnyTvVUIalTck',
    appId: '1:534985466756:web:9168dea49b4734d832f3d1',
    messagingSenderId: '534985466756',
    projectId: 'eux-client',
    authDomain: 'eux-client.firebaseapp.com',
    storageBucket: 'eux-client.firebasestorage.app',
    measurementId: 'G-LLEHSVLXZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANn3P6UtXlYZ0cHV84Vziht6UKRptIUPw',
    appId: '1:534985466756:android:3cd43d9139e2c9ee32f3d1',
    messagingSenderId: '534985466756',
    projectId: 'eux-client',
    storageBucket: 'eux-client.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQ6CZ0vYzeSmkQgKju1gFVcaRyiJlaWU',
    appId: '1:534985466756:ios:1a03cd8f594fdb4b32f3d1',
    messagingSenderId: '534985466756',
    projectId: 'eux-client',
    storageBucket: 'eux-client.firebasestorage.app',
    iosBundleId: 'com.example.euxClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQ6CZ0vYzeSmkQgKju1gFVcaRyiJlaWU',
    appId: '1:534985466756:ios:1a03cd8f594fdb4b32f3d1',
    messagingSenderId: '534985466756',
    projectId: 'eux-client',
    storageBucket: 'eux-client.firebasestorage.app',
    iosBundleId: 'com.example.euxClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmgOO7dqA37r61O3hAm2CnyTvVUIalTck',
    appId: '1:534985466756:web:c9eaede2f53bf12e32f3d1',
    messagingSenderId: '534985466756',
    projectId: 'eux-client',
    authDomain: 'eux-client.firebaseapp.com',
    storageBucket: 'eux-client.firebasestorage.app',
    measurementId: 'G-LPVNY7940E',
  );
}
